import {
	HA2HA_CAPABILITIES,
	HA2HA_CONFLICT_POLICIES,
	HA2HA_PATHS,
	HA2HA_PROTOCOL,
	ha2haEvidenceMetadataSchema,
	ha2haParticipantFrontmatterSchema,
	ha2haTaskFrontmatterSchema,
	ha2haWorkspaceManifestSchema,
} from "@ha2ha/protocol";
import { parse as parseYaml } from "yaml";
import { WorkspaceError } from "./domain";

const EVIDENCE_FILE_PATTERN = /^evidence\/.+\/.+\.md$/u;
const FRONTMATTER_PATTERN = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/u;
const PARTICIPANT_FILE_PATTERN = /^participants\/(.+)\.md$/u;
const RESERVED_MANIFEST_PATH = ".ha2ha/workspace.json";
const TASK_FILE_PATTERN = /^tasks\/(.+)\.md$/u;

export interface WorkspaceCreateFile {
	content: string;
	contentType: string;
	path: string;
}

export function prepareHa2haWorkspaceFiles({
	actor,
	files,
	title,
	workspaceId,
}: {
	actor: string;
	files: WorkspaceCreateFile[];
	title: string | null;
	workspaceId: string;
}): WorkspaceCreateFile[] {
	if (files.some((file) => file.path === RESERVED_MANIFEST_PATH)) {
		throw new WorkspaceError(
			400,
			"reserved_protocol_path",
			`${RESERVED_MANIFEST_PATH} is generated by MDSync for HA2HA workspaces.`
		);
	}

	const taskFiles = files.filter((file) => TASK_FILE_PATTERN.test(file.path));
	const tasks = taskFiles.map((file) => validateTaskFile(file));
	const workspaceTitle = title ?? "HA2HA Workspace";
	const participantPath = `participants/${actor}.md`;
	const generated: WorkspaceCreateFile[] = [
		{
			content: `${JSON.stringify(
				createWorkspaceManifest({ title: workspaceTitle, workspaceId }),
				null,
				2
			)}\n`,
			contentType: "application/json; charset=utf-8",
			path: RESERVED_MANIFEST_PATH,
		},
	];
	if (!files.some((file) => file.path === HA2HA_PATHS.manifestMarkdown)) {
		generated.push({
			content: createManifestMarkdown(workspaceTitle),
			contentType: "text/markdown; charset=utf-8",
			path: HA2HA_PATHS.manifestMarkdown,
		});
	}
	if (!files.some((file) => file.path === HA2HA_PATHS.status)) {
		generated.push({
			content: createStatusMarkdown(tasks),
			contentType: "text/markdown; charset=utf-8",
			path: HA2HA_PATHS.status,
		});
	}
	if (!files.some((file) => file.path === participantPath)) {
		generated.push({
			content: `---\nid: ${actor}\ncan_edit: true\n---\n\n## Current Focus\n\n- ${tasks[0]?.id ?? "No task selected"}\n`,
			contentType: "text/markdown; charset=utf-8",
			path: participantPath,
		});
	}

	const completeFiles = [...files, ...generated];
	validateParticipants(completeFiles);
	validateEvidence(completeFiles, workspaceId);
	validateGeneratedWorkspace(completeFiles, workspaceId);
	return completeFiles;
}

function createWorkspaceManifest({
	title,
	workspaceId,
}: {
	title: string;
	workspaceId: string;
}) {
	return ha2haWorkspaceManifestSchema.parse({
		capabilities: [
			HA2HA_CAPABILITIES.rawRead,
			HA2HA_CAPABILITIES.fileWrite,
			HA2HA_CAPABILITIES.events,
			HA2HA_CAPABILITIES.fileHistory,
			HA2HA_CAPABILITIES.importExportPreservation,
		],
		conflictPolicy: HA2HA_CONFLICT_POLICIES.baseVersionRequired,
		paths: HA2HA_PATHS,
		protocol: HA2HA_PROTOCOL.name,
		protocolVersion: HA2HA_PROTOCOL.version,
		routes: {
			events: `/api/workspaces/${workspaceId}/events`,
			file: `/api/workspaces/${workspaceId}/files`,
			fileVersion: `/api/workspaces/${workspaceId}/files/versions/{version}`,
			fileVersions: `/api/workspaces/${workspaceId}/files/versions`,
			rawEvents: `/w/${workspaceId}/raw/events`,
			rawFile: `/w/${workspaceId}/raw/{path}`,
			rawListing: `/w/${workspaceId}/raw`,
			tree: `/api/workspaces/${workspaceId}/tree`,
		},
		schemaVersions: {
			evidence: HA2HA_PROTOCOL.version,
			task: HA2HA_PROTOCOL.version,
			workspace: HA2HA_PROTOCOL.version,
		},
		title,
		workspaceId,
	});
}

function createManifestMarkdown(title: string) {
	return `# ${title}\n\nThis workspace follows the HA2HA ${HA2HA_PROTOCOL.version} core workspace convention.\n\nMutating writes require an explicit actor and the current \`baseVersion\`. Capability URLs are never stored in workspace content.\n`;
}

function createStatusMarkdown(
	tasks: Array<{ id: string; state: string; title: string }>
) {
	const taskLines = tasks.map(
		(task) => `- ${task.id}: ${task.title} (${task.state})`
	);
	return `# Status\n\n## Current work\n\n${taskLines.join("\n")}\n`;
}

function validateTaskFile(file: WorkspaceCreateFile) {
	const result = ha2haTaskFrontmatterSchema.safeParse(
		parseFrontmatter(file.content, file.path)
	);
	if (!result.success) {
		throw invalidFrontmatter(file.path, "task");
	}
	const pathId = TASK_FILE_PATTERN.exec(file.path)?.[1];
	if (pathId !== result.data.id) {
		throw new WorkspaceError(
			400,
			"invalid_task_path",
			`Task id must match its file name: ${file.path}`
		);
	}
	return result.data;
}

function validateParticipants(files: WorkspaceCreateFile[]) {
	for (const file of files) {
		const pathId = PARTICIPANT_FILE_PATTERN.exec(file.path)?.[1];
		if (!pathId) {
			continue;
		}
		const result = ha2haParticipantFrontmatterSchema.safeParse(
			parseFrontmatter(file.content, file.path)
		);
		if (!result.success) {
			throw invalidFrontmatter(file.path, "participant");
		}
		if (pathId !== result.data.id) {
			throw new WorkspaceError(
				400,
				"invalid_participant_path",
				`Participant id must match its file name: ${file.path}`
			);
		}
	}
}

function validateEvidence(files: WorkspaceCreateFile[], workspaceId: string) {
	for (const file of files) {
		if (!EVIDENCE_FILE_PATTERN.test(file.path)) {
			continue;
		}
		const result = ha2haEvidenceMetadataSchema.safeParse(
			parseFrontmatter(file.content, file.path)
		);
		if (!result.success) {
			throw invalidFrontmatter(file.path, "evidence");
		}
		if (result.data.target && result.data.target.workspaceId !== workspaceId) {
			throw new WorkspaceError(
				400,
				"invalid_evidence_target",
				`Evidence target workspace must match the created workspace: ${file.path}`
			);
		}
	}
}

function validateGeneratedWorkspace(
	files: WorkspaceCreateFile[],
	workspaceId: string
) {
	const manifestFile = files.find(
		(file) => file.path === RESERVED_MANIFEST_PATH
	);
	if (!manifestFile) {
		throw new WorkspaceError(
			500,
			"protocol_generation_failed",
			"MDSync did not generate the HA2HA workspace manifest."
		);
	}
	try {
		const manifest = ha2haWorkspaceManifestSchema.parse(
			JSON.parse(manifestFile.content)
		);
		if (manifest.workspaceId !== workspaceId) {
			throw new Error("Workspace id mismatch.");
		}
	} catch (error) {
		// biome-ignore lint/style/useErrorCause: WorkspaceError forwards ErrorOptions to Error.
		throw new WorkspaceError(
			500,
			"protocol_generation_failed",
			"MDSync generated an invalid HA2HA workspace manifest.",
			{ cause: error }
		);
	}
}

function parseFrontmatter(content: string, path: string): unknown {
	const match = FRONTMATTER_PATTERN.exec(content);
	if (!match?.[1]) {
		throw invalidFrontmatter(path, "HA2HA");
	}
	try {
		return parseYaml(match[1]);
	} catch (error) {
		// biome-ignore lint/style/useErrorCause: WorkspaceError forwards ErrorOptions to Error.
		throw new WorkspaceError(
			400,
			"invalid_protocol_frontmatter",
			`Invalid YAML frontmatter: ${path}`,
			{ cause: error }
		);
	}
}

function invalidFrontmatter(path: string, kind: string) {
	return new WorkspaceError(
		400,
		"invalid_protocol_frontmatter",
		`Invalid ${kind} frontmatter: ${path}`
	);
}
